# Generated by Django 3.2.7 on 2021-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
