# Generated by Django 3.2.7 on 2021-10-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_user',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
