# Generated by Django 3.2.7 on 2021-10-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bot_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_user',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
